# Nombre del ejecutable
TARGET = juego

# Archivos fuente
SOURCES = Main.hs Canon.hs Juego.hs

# Compilación
all:
	ghc -o $(TARGET) $(SOURCES)

# Limpiar los archivos generados
clean:
	rm -f $(TARGET) *.hi *.o
